import os
import json
import httpx
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Any

router = APIRouter()

SYSTEM_PROMPT = """You are an expert network engineer and security analyst specializing in TCP/IP packet capture analysis.

You have been provided with a structured analysis report from a TCP dump capture. This report was generated by 13 specialized analyzers covering:
- Performance metrics (handshake times, retransmissions, zero windows, throughput)
- Security findings (port scans, cleartext credentials, exfiltration indicators, ARP spoofing, IOC matches)
- Protocol analysis (TLS, DNS, HTTP, connection resets)
- Flow analysis and top talkers
- OS/device fingerprinting
- Geo-IP and threat intelligence
- Beacon/C2 detection
- RST forensics
- HTTP object extraction
- DNS mapping
- Timeline of events

The user has told you WHY they captured this TCP dump (their capture context/reason). Use this context to focus your analysis on what matters most to them.

Be specific and actionable. Reference exact metrics, IPs, timestamps, and findings from the report. Avoid generic advice — everything you say should be grounded in the actual data provided.

When you see something suspicious or noteworthy, explain what it means in plain terms first, then give the technical detail.

Format your responses clearly with sections when appropriate. Keep answers focused and avoid repeating the same information unnecessarily."""


class Message(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    report: dict[str, Any]
    capture_reason: str
    messages: list[Message]


class ChatResponse(BaseModel):
    response: str


def _build_report_summary(report: dict) -> str:
    lines = []
    lines.append("=== TCP DUMP ANALYSIS REPORT ===")
    lines.append(f"File: {report.get('filename', 'unknown')}")
    lines.append(f"Total Packets: {report.get('total_packets', 0)}")
    lines.append(f"Duration: {report.get('capture_duration_sec', 0):.1f}s")
    lines.append(f"Unique IPs: {len(report.get('unique_ips', []))}")

    diagnoses = report.get('diagnoses', [])
    if diagnoses:
        lines.append(f"\n--- DIAGNOSES ({len(diagnoses)} total) ---")
        for d in diagnoses:
            lines.append(f"[{d.get('severity','?').upper()}] {d.get('title','')}: {d.get('detail','')}")

    perf = report.get('performance', {})
    if perf:
        lines.append("\n--- PERFORMANCE ---")
        lines.append(f"Avg Handshake: {perf.get('avg_handshake_ms')} ms | P95: {perf.get('p95_handshake_ms')} ms | Max: {perf.get('max_handshake_ms')} ms")
        lines.append(f"Retransmissions: {perf.get('retransmission_count')} ({perf.get('retransmission_rate_pct')}%)")
        lines.append(f"Zero Windows: {perf.get('zero_window_count')}")
        lines.append(f"Avg App Response Delta: {perf.get('avg_delta_ms')} ms | P95: {perf.get('p95_delta_ms')} ms")
        if perf.get('handshake_anomalies'):
            lines.append(f"Slow Handshake Anomalies: {len(perf['handshake_anomalies'])} events")
        if perf.get('slow_response_events'):
            lines.append(f"Slow Response Events: {len(perf['slow_response_events'])} events")

    sec = report.get('security', {})
    if sec:
        lines.append("\n--- SECURITY ---")
        lines.append(f"Port Scan Sources: {len(sec.get('port_scan_sources', []))}")
        lines.append(f"Cleartext Credentials: {len(sec.get('cleartext_credentials', []))}")
        lines.append(f"Protocol/Port Mismatches: {len(sec.get('protocol_port_mismatches', []))}")
        lines.append(f"Exfiltration Indicators: {len(sec.get('exfiltration_indicators', []))}")
        for c in sec.get('cleartext_credentials', [])[:5]:
            lines.append(f"  CRED: {c}")
        for e in sec.get('exfiltration_indicators', [])[:5]:
            lines.append(f"  EXFIL: {e}")

    arp = report.get('arp', {})
    if arp and arp.get('conflicts'):
        lines.append(f"ARP Spoofing Conflicts: {len(arp['conflicts'])}")
        for c in arp['conflicts'][:3]:
            lines.append(f"  IP {c.get('ip')} seen with MACs: {c.get('macs_seen')}")

    ioc = report.get('ioc', {})
    if ioc and ioc.get('matches'):
        lines.append(f"IOC Matches: {len(ioc['matches'])}")
        for m in ioc['matches'][:5]:
            lines.append(f"  [{m.get('severity','?').upper()}] {m.get('ip')} ({m.get('source')}): {m.get('detail')}")

    proto = report.get('protocol', {})
    if proto:
        lines.append("\n--- PROTOCOL ---")
        lines.append(f"Total Connections: {proto.get('total_connections')}")
        lines.append(f"RST Rate: {proto.get('reset_rate_pct')}%")
        lines.append(f"HTTP Error Rate: {proto.get('http_error_rate_pct')}%")
        lines.append(f"TLS Failures: {len(proto.get('tls_failures', []))}")
        lines.append(f"DNS Errors: {len(proto.get('dns_errors', []))}")
        http_status = proto.get('http_status_counts', {})
        if http_status:
            lines.append(f"HTTP Status Codes: {dict(sorted(http_status.items()))}")

    flow = report.get('flow', {})
    if flow:
        lines.append("\n--- FLOWS ---")
        lines.append(f"Total Flows: {flow.get('total_flows')}")
        for t in (flow.get('top_talkers') or [])[:5]:
            lines.append(f"  Top Talker: {t}")

    tls = report.get('tls_deep', {})
    if tls:
        lines.append("\n--- TLS DEEP ---")
        lines.append(f"Weak Cipher Connections: {tls.get('weak_cipher_count')}")
        lines.append(f"Deprecated TLS Versions: {tls.get('deprecated_version_count')}")
        lines.append(f"Unique JA3 Fingerprints: {tls.get('unique_ja3')}")

    geo = report.get('geo', {})
    if geo:
        lines.append("\n--- GEO/IOC ---")
        lines.append(f"External IPs: {len(geo.get('entries', []))}")
        for c in (geo.get('by_country') or [])[:5]:
            lines.append(f"  Country: {c}")

    beacons = report.get('beacons', {})
    if beacons and beacons.get('beacons'):
        lines.append("\n--- BEACONS ---")
        lines.append(f"Beaconing Flows Detected: {len(beacons['beacons'])}")
        for b in beacons['beacons'][:3]:
            lines.append(f"  Beacon: {b}")

    rst = report.get('rst_forensics', {})
    if rst:
        lines.append("\n--- RST FORENSICS ---")
        lines.append(f"Total RSTs: {rst.get('total_resets')}")
        for cause, count in list((rst.get('by_cause') or {}).items())[:5]:
            lines.append(f"  Cause '{cause}': {count} occurrences")

    timeline = report.get('timeline', {})
    if timeline and timeline.get('events'):
        lines.append("\n--- TIMELINE ---")
        lines.append(f"Total Events: {len(timeline['events'])}")
        for e in timeline['events'][:10]:
            lines.append(f"  [{e.get('category','?')}] t={e.get('timestamp','?')}: {e.get('description','')}")

    return "\n".join(lines)


@router.post("/chat")
async def chat(req: ChatRequest):
    try:
        import anthropic
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="anthropic package not installed. Run: pip install anthropic"
        )

    auth_token = os.environ.get("ANTHROPIC_AUTH_TOKEN")
    base_url = os.environ.get("ANTHROPIC_BEDROCK_BASE_URL")
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    use_bedrock = bool(auth_token and base_url)

    if not use_bedrock and not api_key:
        raise HTTPException(
            status_code=500,
            detail="No API credentials found. Set ANTHROPIC_AUTH_TOKEN + ANTHROPIC_BEDROCK_BASE_URL in backend/.env"
        )

    report_summary = _build_report_summary(req.report)
    context_block = (
        f"CAPTURE CONTEXT (user's reason for this capture):\n{req.capture_reason}\n\n"
        f"{report_summary}"
    )

    messages = [
        {
            "role": "user",
            "content": (
                f"Here is the TCP dump analysis report and my capture context:\n\n"
                f"{context_block}\n\n"
                f"Please acknowledge that you've reviewed the report and are ready to answer questions about it."
            ),
        },
        {
            "role": "assistant",
            "content": (
                f"I've reviewed the TCP dump analysis report for {req.report.get('filename', 'your capture')}. "
                f"I can see the full analysis including performance metrics, security findings, protocol data, "
                f"and all results from the 13 analyzers. I understand your context: {req.capture_reason}. "
                f"I'm ready to help — what would you like to know?"
            ),
        },
    ]

    for msg in req.messages:
        if msg.role == "assistant" and "I've reviewed the TCP dump" in msg.content:
            continue
        messages.append({"role": msg.role, "content": msg.content})

    async def event_stream():
        import httpx
        try:
            if use_bedrock:
                model_id = "global.anthropic.claude-sonnet-4-6"
                ca_bundle = os.environ.get(
                    "SSL_CERT_FILE",
                    r"C:\Users\ppenthoi\.claude\certs\salesforce-ca-bundle.pem"
                )
                url = f"{base_url.rstrip('/')}/model/{model_id}/invoke-with-response-stream"
                payload = {
                    "anthropic_version": "bedrock-2023-05-31",
                    "max_tokens": 4096,
                    "system": SYSTEM_PROMPT,
                    "messages": messages,
                }
                headers = {
                    "x-api-key": auth_token,
                    "Content-Type": "application/json",
                    "Accept": "application/vnd.amazon.eventstream",
                }
                async with httpx.AsyncClient(verify=ca_bundle, timeout=120.0) as http:
                    async with http.stream("POST", url, json=payload, headers=headers) as resp:
                        if resp.status_code != 200:
                            body = await resp.aread()
                            yield f"data: {json.dumps({'error': f'Gateway error ({resp.status_code}): {body.decode()}'})}\n\n"
                            return
                        import re, base64
                        async for line in resp.aiter_lines():
                            if not line:
                                continue
                            # AWS EventStream binary format: JSON with base64 "bytes" field
                            # embedded after binary header markers on each line
                            match = re.search(r'"bytes"\s*:\s*"([A-Za-z0-9+/=]+)"', line)
                            if not match:
                                continue
                            try:
                                chunk = json.loads(base64.b64decode(match.group(1)))
                                delta = chunk.get("delta", {})
                                text = delta.get("text", "")
                                if text:
                                    yield f"data: {json.dumps({'text': text})}\n\n"
                            except Exception:
                                continue
            else:
                client = anthropic.AsyncAnthropic(api_key=api_key, timeout=120.0)
                async with client.messages.stream(
                    model="claude-sonnet-4-6",
                    max_tokens=4096,
                    system=SYSTEM_PROMPT,
                    messages=messages,
                ) as stream:
                    async for text in stream.text_stream:
                        yield f"data: {json.dumps({'text': text})}\n\n"
            yield "data: [DONE]\n\n"
        except anthropic.APIStatusError as e:
            yield f"data: {json.dumps({'error': f'Claude API error ({e.status_code}): {e.message}'})}\n\n"
        except httpx.ConnectTimeout:
            yield f"data: {json.dumps({'text': 'The AI chat is not available on this deployment — the network cannot reach the AI gateway. The rest of the TCP Analyzer (analysis, reports, exports) works normally.'})}\n\n"
        except httpx.ConnectError:
            yield f"data: {json.dumps({'text': 'The AI chat is not available on this deployment — the network cannot reach the AI gateway. The rest of the TCP Analyzer (analysis, reports, exports) works normally.'})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )
