import os
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Any

router = APIRouter()

SYSTEM_PROMPT = """You are an expert network engineer and security analyst specializing in TCP/IP packet capture analysis.

You have been provided with a structured analysis report from a TCP dump capture. This report was generated by 13 specialized analyzers covering:
- Performance metrics (handshake times, retransmissions, zero windows, throughput)
- Security findings (port scans, cleartext credentials, exfiltration indicators, ARP spoofing, IOC matches)
- Protocol analysis (TLS, DNS, HTTP, connection resets)
- Flow analysis and top talkers
- OS/device fingerprinting
- Geo-IP and threat intelligence
- Beacon/C2 detection
- RST forensics
- HTTP object extraction
- DNS mapping
- Timeline of events

The user has told you WHY they captured this TCP dump (their capture context/reason). Use this context to focus your analysis on what matters most to them.

Be specific and actionable. Reference exact metrics, IPs, timestamps, and findings from the report. Avoid generic advice — everything you say should be grounded in the actual data provided.

When you see something suspicious or noteworthy, explain what it means in plain terms first, then give the technical detail.

Format your responses clearly with sections when appropriate. Keep answers focused and avoid repeating the same information unnecessarily."""


class Message(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    report: dict[str, Any]
    capture_reason: str
    messages: list[Message]


class ChatResponse(BaseModel):
    response: str


def _build_report_summary(report: dict) -> str:
    lines = []
    lines.append("=== TCP DUMP ANALYSIS REPORT ===")
    lines.append(f"File: {report.get('filename', 'unknown')}")
    lines.append(f"Total Packets: {report.get('total_packets', 0)}")
    lines.append(f"Duration: {report.get('capture_duration_sec', 0):.1f}s")
    lines.append(f"Unique IPs: {len(report.get('unique_ips', []))}")

    diagnoses = report.get('diagnoses', [])
    if diagnoses:
        lines.append(f"\n--- DIAGNOSES ({len(diagnoses)} total) ---")
        for d in diagnoses:
            lines.append(f"[{d.get('severity','?').upper()}] {d.get('title','')}: {d.get('detail','')}")

    perf = report.get('performance', {})
    if perf:
        lines.append("\n--- PERFORMANCE ---")
        lines.append(f"Avg Handshake: {perf.get('avg_handshake_ms')} ms | P95: {perf.get('p95_handshake_ms')} ms | Max: {perf.get('max_handshake_ms')} ms")
        lines.append(f"Retransmissions: {perf.get('retransmission_count')} ({perf.get('retransmission_rate_pct')}%)")
        lines.append(f"Zero Windows: {perf.get('zero_window_count')}")
        lines.append(f"Avg App Response Delta: {perf.get('avg_delta_ms')} ms | P95: {perf.get('p95_delta_ms')} ms")
        if perf.get('handshake_anomalies'):
            lines.append(f"Slow Handshake Anomalies: {len(perf['handshake_anomalies'])} events")
        if perf.get('slow_response_events'):
            lines.append(f"Slow Response Events: {len(perf['slow_response_events'])} events")

    sec = report.get('security', {})
    if sec:
        lines.append("\n--- SECURITY ---")
        lines.append(f"Port Scan Sources: {len(sec.get('port_scan_sources', []))}")
        lines.append(f"Cleartext Credentials: {len(sec.get('cleartext_credentials', []))}")
        lines.append(f"Protocol/Port Mismatches: {len(sec.get('protocol_port_mismatches', []))}")
        lines.append(f"Exfiltration Indicators: {len(sec.get('exfiltration_indicators', []))}")
        for c in sec.get('cleartext_credentials', [])[:5]:
            lines.append(f"  CRED: {c}")
        for e in sec.get('exfiltration_indicators', [])[:5]:
            lines.append(f"  EXFIL: {e}")

    arp = report.get('arp', {})
    if arp and arp.get('conflicts'):
        lines.append(f"ARP Spoofing Conflicts: {len(arp['conflicts'])}")
        for c in arp['conflicts'][:3]:
            lines.append(f"  IP {c.get('ip')} seen with MACs: {c.get('macs_seen')}")

    ioc = report.get('ioc', {})
    if ioc and ioc.get('matches'):
        lines.append(f"IOC Matches: {len(ioc['matches'])}")
        for m in ioc['matches'][:5]:
            lines.append(f"  [{m.get('severity','?').upper()}] {m.get('ip')} ({m.get('source')}): {m.get('detail')}")

    proto = report.get('protocol', {})
    if proto:
        lines.append("\n--- PROTOCOL ---")
        lines.append(f"Total Connections: {proto.get('total_connections')}")
        lines.append(f"RST Rate: {proto.get('reset_rate_pct')}%")
        lines.append(f"HTTP Error Rate: {proto.get('http_error_rate_pct')}%")
        lines.append(f"TLS Failures: {len(proto.get('tls_failures', []))}")
        lines.append(f"DNS Errors: {len(proto.get('dns_errors', []))}")
        http_status = proto.get('http_status_counts', {})
        if http_status:
            lines.append(f"HTTP Status Codes: {dict(sorted(http_status.items()))}")

    flow = report.get('flow', {})
    if flow:
        lines.append("\n--- FLOWS ---")
        lines.append(f"Total Flows: {flow.get('total_flows')}")
        for t in (flow.get('top_talkers') or [])[:5]:
            lines.append(f"  Top Talker: {t}")

    tls = report.get('tls_deep', {})
    if tls:
        lines.append("\n--- TLS DEEP ---")
        lines.append(f"Weak Cipher Connections: {tls.get('weak_cipher_count')}")
        lines.append(f"Deprecated TLS Versions: {tls.get('deprecated_version_count')}")
        lines.append(f"Unique JA3 Fingerprints: {tls.get('unique_ja3')}")

    geo = report.get('geo', {})
    if geo:
        lines.append("\n--- GEO/IOC ---")
        lines.append(f"External IPs: {len(geo.get('entries', []))}")
        for c in (geo.get('by_country') or [])[:5]:
            lines.append(f"  Country: {c}")

    beacons = report.get('beacons', {})
    if beacons and beacons.get('beacons'):
        lines.append("\n--- BEACONS ---")
        lines.append(f"Beaconing Flows Detected: {len(beacons['beacons'])}")
        for b in beacons['beacons'][:3]:
            lines.append(f"  Beacon: {b}")

    rst = report.get('rst_forensics', {})
    if rst:
        lines.append("\n--- RST FORENSICS ---")
        lines.append(f"Total RSTs: {rst.get('total_resets')}")
        for cause, count in list((rst.get('by_cause') or {}).items())[:5]:
            lines.append(f"  Cause '{cause}': {count} occurrences")

    timeline = report.get('timeline', {})
    if timeline and timeline.get('events'):
        lines.append("\n--- TIMELINE ---")
        lines.append(f"Total Events: {len(timeline['events'])}")
        for e in timeline['events'][:10]:
            lines.append(f"  [{e.get('category','?')}] t={e.get('timestamp','?')}: {e.get('description','')}")

    return "\n".join(lines)


@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(
            status_code=500,
            detail="ANTHROPIC_API_KEY is not set. Add it to the systemd service environment."
        )

    try:
        import anthropic
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="anthropic package not installed. Run: pip install anthropic"
        )

    client = anthropic.AsyncAnthropic(api_key=api_key)

    report_summary = _build_report_summary(req.report)
    context_block = (
        f"CAPTURE CONTEXT (user's reason for this capture):\n{req.capture_reason}\n\n"
        f"{report_summary}"
    )

    messages = [
        {
            "role": "user",
            "content": (
                f"Here is the TCP dump analysis report and my capture context:\n\n"
                f"{context_block}\n\n"
                f"Please acknowledge that you've reviewed the report and are ready to answer questions about it."
            ),
        },
        {
            "role": "assistant",
            "content": (
                f"I've reviewed the TCP dump analysis report for {req.report.get('filename', 'your capture')}. "
                f"I can see the full analysis including performance metrics, security findings, protocol data, "
                f"and all results from the 13 analyzers. I understand your context: {req.capture_reason}. "
                f"I'm ready to help — what would you like to know?"
            ),
        },
    ]

    for msg in req.messages:
        if msg.role == "assistant" and "I've reviewed the TCP dump" in msg.content:
            continue
        messages.append({"role": msg.role, "content": msg.content})

    try:
        async with client.messages.stream(
            model="claude-opus-4-8",
            max_tokens=8192,
            system=SYSTEM_PROMPT,
            thinking={"type": "adaptive"},
            messages=messages,
        ) as stream:
            final = await stream.get_final_message()

        text = next(
            (block.text for block in final.content if block.type == "text"),
            ""
        )
        return ChatResponse(response=text)

    except anthropic.APIStatusError as e:
        raise HTTPException(status_code=500, detail=f"Claude API error ({e.status_code}): {e.message}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Chat error: {e}")
